/** Types declaration for protobuf
 * This file is auto generated by utils/protobuf/proto2ts.ts
 * Do not edit this file directly.
 *
 * @version 1.0.3
 * @date Fri Nov 21 2025 20:43:53 GMT+0800 (中国标准时间)
 * @author Aluria
 * 
 * @source D:\Program\JS\GI\Convertor\utils\protobuf/gia.proto
 * @dest D:/Program/JS/GI/Convertor/utils/protobuf/gia.proto.ts
 * @program file:///D:/Program/JS/GI/Convertor/utils/protobuf/proto2ts.ts
 */

export const NodeUnit$Id$Type = {
  Unknown1: 0,
  Node: 1,
  Basic: 5,
  AffiliatedNode: 23,
} as const;
export const NodeUnit$Id$NodeType = {
  Unknown2: 0,
  ClientGraph: 3,
  StructureDefinition: 15,
} as const;
export const NodeUnit$Type = {
  Unknown: 0,
  EntityNode: 9,
  BooleanFilter: 10,
  Skills: 11,
  CompositeGraph: 12,
  StatusNode: 22,
  ClassNode: 23,
  StructureDefinition: 29,
  ItemNode: 46,
  IntegerFilter: 47,
} as const;
export const CompositeDef$Type$Kind = {
  Unknown: 0,
  Composite: 1000,
  Assemble: 1003,
  Split: 1004,
  Modify: 1005,
} as const;
export const NodeGraph$Id$Class = {
  Unknown1: 0,
  UserDefined: 10000,
  SystemDefined: 10001,
} as const;
export const NodeGraph$Id$Type = {
  Unknown2: 0,
  BasicNode: 20000,
  BooleanFilter: 20001,
  Skills: 20002,
  StatusNode: 20003,
  ClassNode: 20004,
  ItemNode: 20005,
  IntegerFilter: 20006,
} as const;
export const NodeGraph$Id$Kind = {
  Unknown3: 0,
  NodeGraph: 21001,
  CompositeGraph: 21002,
  SysCall: 22000,
  SysGraph: 22001,
} as const;
export const VarType = {
  UnknownVar: 0,
  Entity: 1,
  GUID: 2,
  Integer: 3,
  Boolean: 4,
  Float: 5,
  String: 6,
  GUIDList: 7,
  IntegerList: 8,
  BooleanList: 9,
  FloatList: 10,
  StringList: 11,
  Vector: 12,
  EntityList: 13,
  EnumItem: 14,
  VectorList: 15,
  Faction: 17,
  Configuration: 20,
  Prefab: 21,
  ConfigurationList: 22,
  PrefabList: 23,
  FactionList: 24,
  Struct: 25,
  StructList: 26,
  Dictionary: 27,
} as const;
export const VarBase$Class = {
  Unknown: 0,
  IdBase: 1,
  IntBase: 2,
  FloatBase: 4,
  StringBase: 5,
  EnumBase: 6,
  VectorBase: 7,
  NodeValueBase: 10000,
  StructBase: 10001,
  ArrayBase: 10002,
  MapBase: 10003,
  MapPair: 10007,
} as const;
export const VarBase$ItemType$Inner$Kind = {
  Normal: 0,
  Struct: 1,
  Pair: 2,
} as const;
export const NodeProperty$Type = {
  Unknown: 0,
  Server: 20000,
  Client: 20002,
} as const;
export const NodePin$Index$Kind = {
  Unknown: 0,
  InFlow: 1,
  OutFlow: 2,
  InParam: 3,
  OutParam: 4,
} as const;
