/** Types declaration for protobuf
 * This file is auto generated by utils/protobuf/proto2ts.ts
 * Do not edit this file directly.
 *
 * @version 1.0.3
 * @date Fri Nov 21 2025 17:57:45 GMT+0800 (中国标准时间)
 * @author Aluria
 */

interface Root {
  graph: NodeUnit; // 1
  utils: NodeUnit[]; // 2
  filePath: string; // 3
}
interface NodeUnit {
  id: NodeUnit$Id; // 1
  relatedIds: NodeUnit$Id[]; // 2
  name: string; // 3
  type: NodeUnit$Type; // 5
  /** One of the field: graphType */
  graph?: NodeGraphWrapper; // 13
  /** One of the field: graphType */
  compositeDef?: CompositeDefWrapper; // 14
  /** One of the field: graphType */
  structureDef?: StructureDefWrapper; // 22
}
interface NodeUnit$Id {
  type: NodeUnit$Id$Type; // 2
  kind?: NodeUnit$Id$NodeType; // 3
  id: number; // 4
}
declare enum NodeUnit$Id$Type {
  Unknown1 = 0,
  Node = 1,
  Basic = 5,
  AffiliatedNode = 23,
}
declare enum NodeUnit$Id$NodeType {
  Unknown2 = 0,
  ClientGraph = 3,
  StructureDefinition = 15,
}
declare enum NodeUnit$Type {
  Unknown = 0,
  EntityNode = 9,
  BooleanFilter = 10,
  Skills = 11,
  CompositeGraph = 12,
  StatusNode = 22,
  ClassNode = 23,
  StructureDefinition = 29,
  ItemNode = 46,
  IntegerFilter = 47,
}
interface NodeGraphWrapper {
  inner: NodeGraphWrapper$InnerWrapper; // 1
}
interface NodeGraphWrapper$InnerWrapper {
  graph: NodeGraph; // 1
}
interface CompositeDefWrapper {
  inner: CompositeDefWrapper$InnerWrapper; // 1
}
interface CompositeDefWrapper$InnerWrapper {
  def: CompositeDef; // 1
}
interface CompositeDef {
  id: CompositeDef$Id; // 4
  inflows: CompositeDef$ControlFlow[]; // 100
  outflows: CompositeDef$ControlFlow[]; // 101
  inputs: CompositeDef$ParameterFlow[]; // 102
  outputs: CompositeDef$ParameterFlow[]; // 103
  type: CompositeDef$Type; // 107
  name: string; // 200
  description: string; // 201
}
interface CompositeDef$Id {
  genericId: NodeGraph$Id; // 1
  concreteId: NodeGraph$Id; // 2
  graphId: NodeGraph$Id; // 4
}
interface CompositeDef$ParameterFlow {
  name: string; // 1
  visible: boolean; // 2
  index: NodePin$Index; // 3
  type: CompositeDef$ParameterFlow$Type; // 4
  pinIndex: number; // 8
}
interface CompositeDef$ParameterFlow$Type {
  class: VarBase$Class; // 1
  type1: VarType; // 3
  type2: VarType; // 4
  /** One of the field: type */
  mapType?: CompositeDef$ParameterFlow$Type$MapType; // 105
  valueId: CompositeDef$ParameterFlow$Type$ID; // 104
}
interface CompositeDef$ParameterFlow$Type$MapType {
  key: VarType; // 3
  value: VarType; // 4
}
interface CompositeDef$ParameterFlow$Type$ID {
  id: number; // 2
}
interface CompositeDef$ControlFlow {
  name: string; // 1
  visible: boolean; // 2
  index: NodePin$Index; // 3
  description: string; // 4
  pinIndex: number; // 8
}
interface CompositeDef$Type {
  kind: CompositeDef$Type$Kind; // 1
  /** One of the field: parent */
  assemble?: CompositeDef$Type$Id; // 104
  /** One of the field: parent */
  split?: CompositeDef$Type$Id; // 105
  /** One of the field: parent */
  modify?: CompositeDef$Type$Id; // 106
}
declare enum CompositeDef$Type$Kind {
  Unknown = 0,
  Composite = 1000,
  Assemble = 1003,
  Split = 1004,
  Modify = 1005,
}
interface CompositeDef$Type$Id {
  id: number; // 1
}
interface NodeGraph {
  id: NodeGraph$Id; // 1
  name: string; // 2
  nodes: GraphNode[]; // 3
  compositePins: CompositePin[]; // 4
  graphValues: GraphVariable[]; // 6
  affiliations: GraphAffiliation[]; // 7
}
interface NodeGraph$Id {
  class: NodeGraph$Id$Class; // 1
  type: NodeGraph$Id$Type; // 2
  kind: NodeGraph$Id$Kind; // 3
  id: number; // 5
}
declare enum NodeGraph$Id$Class {
  Unknown1 = 0,
  UserDefined = 10000,
  SystemDefined = 10001,
}
declare enum NodeGraph$Id$Type {
  Unknown2 = 0,
  BasicNode = 20000,
  BooleanFilter = 20001,
  Skills = 20002,
  StatusNode = 20003,
  ClassNode = 20004,
  ItemNode = 20005,
  IntegerFilter = 20006,
}
declare enum NodeGraph$Id$Kind {
  Unknown3 = 0,
  NodeGraph = 21001,
  CompositeGraph = 21002,
  SysCall = 22000,
  SysGraph = 22001,
}
interface GraphAffiliation {
  info: GraphAffiliation$Info; // 1
  type: GraphAffiliation$Type; // 2
}
interface GraphAffiliation$Info {
  source: NodeGraph$Id; // 1
  typeXxx: number; // 2
  alwaysOneXxxx: number; // 3
  /** One of the field: extend */
  structId?: VarBase$ItemType$StructItem; // 100
}
interface GraphAffiliation$Type {
  type: number; // 1
}
interface StructureDefWrapper {
  def: StructureDefWrapper$StructureDef; // 1
}
interface StructureDefWrapper$StructureDef {
  genericField: StructureDefWrapper$Field; // 1
  connectField: StructureDefWrapper$Field; // 2
  index: number; // 3
  itemCount: number; // 4
}
interface StructureDefWrapper$Field {
  id: number; // 1
  vars: StructureDefWrapper$VarDef[]; // 3
  structName: string; // 501
  classBase: number; // 502
  index: number; // 503
}
interface StructureDefWrapper$VarDef {
  id: StructureDefWrapper$VarDef$Id; // 1
  def: StructureDefWrapper$VarDef$Content; // 3
  name: string; // 5
  name2: string; // 501
  type: VarType; // 502
  index: number; // 503
}
interface StructureDefWrapper$VarDef$SubType {
  xxx: number; // 1
  xxxx: number; // 2
  key: VarType; // 502
  value: VarType; // 503
  valueId: number; // 504
}
interface StructureDefWrapper$VarDef$Id {
  type: VarType; // 1
  sub: StructureDefWrapper$VarDef$SubType; // 2
}
interface StructureDefWrapper$VarDef$Content {
  type: VarType; // 1
  sub: StructureDefWrapper$VarDef$SubType; // 2
  /** One of the field: val */
  intVal?: IntBaseValue; // 13
  /** One of the field: val */
  boolVal?: EnumBaseValue; // 14
  /** One of the field: val */
  strVal?: StringBaseValue; // 16
}
declare enum VarType {
  UnknownVar = 0,
  Entity = 1,
  GUID = 2,
  Integer = 3,
  Boolean = 4,
  Float = 5,
  String = 6,
  GUIDList = 7,
  IntegerList = 8,
  BooleanList = 9,
  FloatList = 10,
  StringList = 11,
  Vector = 12,
  EntityList = 13,
  EnumItem = 14,
  VectorList = 15,
  Faction = 17,
  Configuration = 20,
  Prefab = 21,
  ConfigurationList = 22,
  PrefabList = 23,
  FactionList = 24,
  Struct = 25,
  StructList = 26,
  Dictionary = 27,
}
interface GraphVariable {
  name: string; // 2
  type: VarType; // 3
  values: VarBase; // 4
  exposed: boolean; // 5
  structId: number; // 6
  keyType: VarType; // 7
  valueType: VarType; // 8
}
interface VarBase {
  class: VarBase$Class; // 1
  alreadySetVal: boolean; // 2
  itemType: VarBase$ItemType; // 4
  structInfo?: VarBase$StructInfo; // 5
  /** One of the field: baseValues */
  bId?: IdBaseValue; // 101
  /** One of the field: baseValues */
  bInt?: IntBaseValue; // 102
  /** One of the field: baseValues */
  bFloat?: FloatBaseValue; // 104
  /** One of the field: baseValues */
  bString?: StringBaseValue; // 105
  /** One of the field: baseValues */
  bEnum?: EnumBaseValue; // 106
  /** One of the field: baseValues */
  bVector?: VectorBaseValue; // 107
  /** One of the field: baseValues */
  bStruct?: StructBaseValue; // 108
  /** One of the field: baseValues */
  bArray?: ArrayBaseValue; // 109
  /** One of the field: baseValues */
  bNodeValue?: NodeValueBaseValue; // 110
  /** One of the field: baseValues */
  bMapPair?: MapPairBaseValue; // 111
  /** One of the field: baseValues */
  bMap?: MapBaseValue; // 112
}
declare enum VarBase$Class {
  Unknown = 0,
  IdBase = 1,
  IntBase = 2,
  FloatBase = 4,
  StringBase = 5,
  EnumBase = 6,
  VectorBase = 7,
  NodeValueBase = 10000,
  StructBase = 10001,
  ArrayBase = 10002,
  MapBase = 10003,
  MapPair = 10007,
}
interface VarBase$ItemType {
  classBase: number; // 1
  itemType: VarBase$ItemType$Inner; // 100
}
interface VarBase$ItemType$StructItem {
  structId: number; // 1
}
interface VarBase$ItemType$Inner {
  type: VarType; // 1
  kind: VarBase$ItemType$Inner$Kind; // 2
  /** One of the field: id */
  item?: VarBase$ItemType$StructItem; // 100
  /** One of the field: id */
  items?: VarBase$ItemType$Inner$PairItems; // 101
}
declare enum VarBase$ItemType$Inner$Kind {
  Normal = 0,
  Struct = 1,
  Pair = 2,
}
interface VarBase$ItemType$Inner$PairItems {
  key: VarType; // 1
  value: VarType; // 2
  structId: number; // 3
}
interface VarBase$StructInfo {
  xxx: number; // 1
  inner: VarBase$StructInfo$Inner; // 100
}
interface VarBase$StructInfo$Inner {
  xxx: number; // 1
}
interface IdBaseValue {
  val: number; // 1
}
interface IntBaseValue {
  val: number; // 1
}
interface FloatBaseValue {
  val: number; // 1
}
interface StringBaseValue {
  val: string; // 1
}
interface EnumBaseValue {
  val: number; // 1
}
interface VectorBaseValue {
  val: VectorBaseValue$Vec; // 1
}
interface VectorBaseValue$Vec {
  x: number; // 1
  y: number; // 2
  z: number; // 3
}
interface StructBaseValue {
  items: VarBase[]; // 1
}
interface ArrayBaseValue {
  entries: VarBase[]; // 1
}
interface MapBaseValue {
  mapPairs: VarBase[]; // 1
}
interface MapPairBaseValue {
  key: VarBase; // 1
  value: VarBase; // 2
}
interface NodeValueBaseValue {
  classBase: number; // 1
  value: VarBase; // 2
  wrapper: NodeValueBaseValue$Wrapper; // 5
}
interface NodeValueBaseValue$Wrapper {
  classBase: number; // 4
  inner: NodeValueBaseValue$Wrapper$Inner; // 100
}
interface NodeValueBaseValue$Wrapper$Inner {
  wrapper: NodeValueBaseValue$Wrapper$Inner$Wrapper; // 1
}
interface NodeValueBaseValue$Wrapper$Inner$Wrapper {
  class: VarBase$Class; // 1
  /** One of the field: type */
  item?: VarBase$ItemType$StructItem; // 100
}
interface GraphNode {
  nodeIndex: number; // 1
  genericId: NodeProperty; // 2
  concreteId: NodeProperty; // 3
  pins: NodePin[]; // 4
  x: number; // 5
  y: number; // 6
  usingStruct: GraphAffiliation$Info[]; // 10
}
interface NodeProperty {
  class: NodeGraph$Id$Class; // 1
  type: NodeProperty$Type; // 2
  kind: NodeGraph$Id$Kind; // 3
  nodeId: number; // 5
}
declare enum NodeProperty$Type {
  Unknown = 0,
  Server = 20000,
  Client = 20002,
}
interface NodePin {
  i1: NodePin$Index; // 1
  i2: NodePin$Index; // 2
  value: VarBase; // 3
  type: VarType; // 4
  connects: NodeConnection[]; // 5
}
interface NodePin$Index {
  kind: NodePin$Index$Kind; // 1
  index: number; // 2
}
declare enum NodePin$Index$Kind {
  Unknown = 0,
  InFlow = 1,
  OutFlow = 2,
  InParam = 3,
  OutParam = 4,
}
interface NodeConnection {
  id: number; // 1
  connect: NodePin$Index; // 2
  connect2: NodePin$Index; // 3
}
interface CompositePin {
  outerPin: NodePin$Index; // 1
  innerNodeId: number; // 2
  innerPin: NodePin$Index; // 3
  innerPin2: NodePin$Index; // 4
}

